### ISSUE TITLE
Adding lines in code blocks breaks layout

### ISSUE THREAD

**Issue by waywaaard** [GitbookIO/draft-markup#8]
When hitting <kbd>Enter</kbd> to insert a new line inside an code block (fence) , the new line is not inside the current element.

See image:
![image](https://cloud.githubusercontent.com/assets/1634468/14199727/22c037a6-f7e7-11e5-835a-2056cc23ae1c.png)

**Comment by SamyPesse** [comment]
This module will only take care of the parsing/output of markdown; it'll no longer contains the react components.

We are publishing [react-markup-editor](https://github.com/GitbookIO/react-markup-editor) which is using `draft-markup` and provide a complete WYSIWYG editor (work in progress :construction_worker: )

This issue will be taken care in `react-markup-editor`
