### ISSUE TITLE
Images Editing broken

### ISSUE THREAD

**Issue by waywaaard** [GitbookIO/draft-markup#9]
When clicking on an <em>image</em> and dismissing the dialog, the image will be removed. The undo does not recover the operation.

**Comment by SamyPesse** [comment]
This module will only take care of the parsing/output of markdown; it'll no longer contains the react components.

We are publishing [react-markup-editor](https://github.com/GitbookIO/react-markup-editor) which is using `draft-markup` and provide a complete WYSIWYG editor (work in progress :construction_worker: )
